version: 2

updates:

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly

  # devcontainers
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  # NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      mstest:
        applies-to: version-updates
        patterns:
          - "Microsoft.NET.Test.Sdk"
          - "Microsoft.CodeCoverage"
          - "Microsoft.Testing.*"
          - "Microsoft.TestPlatform.*"
          - "MSTest.*"
      spectre:
        applies-to: version-updates
        patterns:
          - "Spectre.Console"
          - "Spectre.Console.*"
